# Generated by Django 4.2.16 on 2024-12-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='zipcode',
            field=models.IntegerField(null=True),
        ),
    ]
