# Generated by Django 4.1.5 on 2024-11-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M', 'Pooja Samgri'), ('H', 'Havan Samagri'), ('S', 'Spices'), ('J', 'Jadi Booti'), ('JM', 'Jap Mala'), ('I', 'Idols'), ('R', 'Roodraksh')], max_length=2, null=True),
        ),
    ]
