# Generated by Django 4.2.16 on 2024-12-07 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_pandit'),
    ]

    operations = [
        migrations.AddField(
            model_name='pandit',
            name='pincode',
            field=models.IntegerField(null=True),
        ),
    ]
