# Generated by Django 4.2.16 on 2024-12-07 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_pandit_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pandit',
            name='availability',
        ),
    ]
