# Generated by Django 4.2.16 on 2024-12-07 17:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_pandit_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 12, 7, 17, 42, 54, 717944, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
