# Generated by Django 4.2.16 on 2025-01-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_product_product_image_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='zipcode',
            new_name='pincode',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='locality',
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
