# Generated by Django 4.2.16 on 2025-01-18 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_orderplaced_address_orderplaced_district_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='city',
            new_name='district',
        ),
    ]
