# Generated by Django 4.2.16 on 2025-01-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_city_customer_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='razorpay_order_id',
            field=models.CharField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
